<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<?php echo $this->basepath('img/login.jpg')?>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Login</h1>
                    <hr class="small">
                </div>
            </div>
        </div>
    </div>
</header>
<!-- End Page Header -->

	
<!-- Main Container -->
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  
                <?php
                $form = $this->loginForm;
                $form->prepare();
                $form->setAttribute('action', $this->url('zfcuser/login'));
                $form->setAttribute('method', 'post');
                ?>
                 
                <?php echo $this->form()->openTag($form) ?>
                <?php foreach ($form as $element) : ?>
                 
                    <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                        <?php
                            if ('submit' != $element->getAttribute('type')) { ?>
                                <label class="control-label"><?php echo $element->getLabel() ?></label>
                                <?php
                                $element->setAttribute('class', 'form-control')
                                        ->setAttribute('placeholder', $element->getLabel());
                            } else {
                                $element->setAttribute('class', 'btn btn-success');
                            }
                            echo $this->formElement($element);
                            if ($this->formElementErrors($element)) : ?>
                                <?php
                                echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<p class="help-block">')
                                    ->setMessageSeparatorString('</p><p class="help-block">')
                                    ->setMessageCloseString('</p>')
                                    ->render($element);
                                ?>
                            <?php endif; ?>
                    </div>
                 
                <?php
                endforeach;
                 
                echo $this->form()->closeTag() ?>
                 
                <?php if ($this->enableRegistration) : ?>
                <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
                <?php endif; ?>
            </div>
        </div>
    </div>
<!-- End Main Container -->
