<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<?php echo $this->basepath('img/register.jpg')?>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Register</h1>
                    <hr class="small">
                </div>
            </div>
        </div>
    </div>
</header>
<!-- End Page Header -->

	
<!-- Main Container -->
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
 
                <?php
                if (!$this->enableRegistration) {
                    print "Registration is disabled";
                    return;
                }
                $form = $this->registerForm;
                $form->prepare();
                $form->setAttribute('action', $this->url('zfcuser/register'));
                $form->setAttribute('method', 'post');
                echo $this->form()->openTag($form);
                ?>
                 
                <?php foreach ($form as $element) : ?>
                 
                    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                        <?php
                            if ('submit' != $element->getAttribute('type')) { ?>
                                <label class="control-label"><?php echo $element->getLabel() ?></label>
                                <?php
                                $element->setAttribute('class', 'form-control')
                                        ->setAttribute('placeholder', $element->getLabel());
                            } else {
                                $element->setAttribute('class', 'btn btn-success');
                            }
                            if ($element instanceof Zend\Form\Element\Captcha) {
                                echo $this->formCaptcha($element);
                            } else {
                                echo $this->formElement($element);
                            }
                            if ($this->formElementErrors($element)) : ?>
                                <?php
                                echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<p class="help-block">')
                                    ->setMessageSeparatorString('</p><p class="help-block">')
                                    ->setMessageCloseString('</p>')
                                    ->render($element);
                                ?>
                            <?php endif; ?>
                    </div>
                 
                <?php
                endforeach;
                    if ($this->redirect): ?>
                        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                    <?php endif ?>
                <?php echo $this->form()->closeTag() ?>
                
        	</div>
        </div>
    </div>
<!-- End Main Container -->
                