    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('<?php echo $this->basepath('img/home-bg.jpg')?>')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Scarpa Blog</h1>
                        <hr class="small">
                        <span class="subheading">The blog where only scarpa maters</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <?php foreach ($this->articles as $articles) {
                        $date = $articles->getDate()->format("F j, Y");?>
                <div class="post-preview">
                    <a href="/articles/view/<?php echo $articles->getId()?>">
                        <h2 class="post-title">
                           <?php 
                           $titre = $articles->getTitre();
                           if (strlen($titre) > 80)
                                echo substr($titre, 0, 77) . '...'; 
                           else 
                               echo $titre;
                           ?>
                        </h2>
                        <h3 class="post-subtitle">
                        <?php 
                           $contenu = $articles->getContenu();
                           if (strlen($contenu) > 100)
                                echo substr($contenu, 0, 97) . '...'; 
                           else 
                               echo $contenu;
                           ?>
                        </h3>
                    </a>
                    <?php if($this->userRole == 'auteur') {?>
                    	<?php if($articles->getEn_ligne()) {?>
                    	<a href="/articles/desactiver/<?php echo $articles->getId()?>"><h3 class="post-subtitle" style="text-align:right">Click for DISABLE</h3></a>
                        <?php } 
                        else {?>
                        <a href="/articles/activer/<?php echo $articles->getId()?>"><h3 class="post-subtitle" style="text-align:right">Click for ENABLE</h3></a>
                    	<?php }
                           }?>
                    <p class="post-meta">Posted on <?php echo $date?></p>
                </div>
                <hr>
                <?php } ?>
            </div>
        </div>
    </div>

