<header class="intro-header" style="background-image: url('<?php echo $this->basepath('img/veiw_article.jpg')?>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1 style="text-align: center;"><?php echo $this->article->getTitre() ?></h1>
                    <hr>
                    <span class="meta" style="text-align: right;">Posted on <?php echo $this->article->getDate()->format("F j, Y") ?></span>
                </div>
            </div>
        </div>
    </div>
</header>

<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<p><?php echo $this->article->getContenu() ?></p>
				 <form name="createComment" id="createForm" action="<?php echo $this->url('articles - createCommentaire'); ?>" method="post" class="error">
				 <input type="hidden" name="article_id" value="<?php echo $this->article->getId() ?>">
				 <?php foreach ($this->commentaires as $commentaire) { ?>
            		<div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        	<p><strong><?php echo $commentaire->getNom() ?></strong>, <?php echo $commentaire->getDate()->format("F j, Y") ?> 
                        		<?php if($this->userRole == 'auteur') { ?> - 
                            		<?php if($commentaire->getValidation()) {?>
                            			<a style="color:red" href="/commentaire/desactiver/<?php echo $this->article->getId() ?>/<?php echo $commentaire->getId() ?>" >Disable this comment</a> 
                            		<?php } else {?>
                            			<a style="color:green" href="/commentaire/activer/<?php echo $this->article->getId() ?>/<?php echo $commentaire->getId() ?>">Enable this comment</a>
                            		<?php }?>
                            		
                        		<?php } ?></p>
                            <p class="help-block text-danger"><?php echo $commentaire->getText() ?></p>
                    	</div>
            		</div>
            		<?php }?>
                	<div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" name="commentaire" required="" data-validation-required-message="Please enter a message." aria-invalid="false"></textarea>
                            <p class="help-block text-danger"></p>
                    	</div>
            		</div>
            		<div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
    			</form>
            </div>
        </div>
    </div>
</article>

