<header class="intro-header" style="background-image: url('<?php echo $this->basepath('img/veiw_article.jpg')?>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1 style="text-align: center;"><?php echo $this->article->getTitre() ?></h1>
                    <hr>
                    <span class="meta" style="text-align: right;">Posted on <?php echo $this->article->getDate()->format("F j, Y") ?></span>
                </div>
            </div>
        </div>
    </div>
</header>

<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<?php echo $this->article->getContenu() ?>
            </div>
        </div>
    </div>
</article>

