<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sSCARPA%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Scarpa est un site de vente de chaussure italienne en ligne.'), \Zend\Version\Version::VERSION) ?></p>
    
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('<img src="http://i2.cdscdn.com/pdt2/n/v/y/1/700x700/vewznvy/rw/vans-skate-shoes-era-mixte.jpg" width="200" height="180"/>'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Acheter ce Scarpa') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

     <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('<img src="http://www.airmax90noir.com/2603-7876-thickbox/livraison-gratuite-chaussures-homme-nike-zoom-huarache-tr-mi-flash-air-max-chaussures-noir-gris.jpg" width="200" height="180"/>'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Acheter ce Scarpa') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

     <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('<img src="http://i2.cdscdn.com/pdt2/n/v/y/1/700x700/vewznvy/rw/vans-skate-shoes-era-mixte.jpg" width="200" height="180"/>'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Acheter ce Scarpa') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
